version: 2.1

orbs:
  win: circleci/windows@1.0.0

workflows:
  version: 2
  test:
    jobs:
      - test_linux:
          name: .NET Core 3.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          build-target-framework: netcoreapp3.1
          test-target-framework: netcoreapp3.1
      - test_linux:
          name: .NET 6.0
          docker-image: mcr.microsoft.com/dotnet/sdk:6.0-focal
          build-target-framework: net6.0
          test-target-framework: net6.0
      - test_windows:
          name: .NET Framework 4.6.2
          build-target-framework: net462
          test-target-framework: net462

jobs:
  test_linux:
    parameters:
      docker-image:
        type: string
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-framework>>
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.TestHelpers
      - run:
          name: run tests
          command: |
            dotnet test \
              --logger:"junit;LogFilePath=/tmp/circle-reports/unit-tests.xml" \
              test/LaunchDarkly.TestHelpers.Tests/LaunchDarkly.TestHelpers.Tests.csproj
      - store_test_results:
          path: /tmp/circle-reports

  test_windows:
    parameters:
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      BUILDFRAMEWORKS: <<parameters.build-target-framework>>
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.TestHelpers
      - run:
          name: run tests
          command: |
            dotnet test \
              -l "junit;LogFilePath=/tmp/circle-reports/unit-tests.xml" \
              test/LaunchDarkly.TestHelpers.Tests/LaunchDarkly.TestHelpers.Tests.csproj
      - store_test_results:
          path: /tmp/circle-reports
