version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.TestHelpers
    description: NuGet

jobs:
  - docker: {}
    template:
      name: dotnet-linux
    env:
      LD_RELEASE_TEST_TARGET_FRAMEWORK: net50
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

documentation:
  gitHubPages: true
  title: LaunchDarkly .NET Test Helpers
